import App from './components/header'
import './globals.css'
import { Andika } from 'next/font/google'
 
const andika = Andika({
  weight: ['400','700'],
  subsets: ['latin'],
  display: 'swap',
})



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={andika.className}>

      <body>
      <App/>
      {children}
      </body>
    </html>
  )
}
